// <auto-generated />
using System;
using ColegioSanJose.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Colegio_San_Jose.Migrations
{
    [DbContext(typeof(ColegioSanJoseContext))]
    [Migration("20251107065851_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColegioSanJose.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Alumnos__3214EC07A560DDDF");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Serrano",
                            Email = "nicole.serrano@colegio.edu",
                            FechaNacimiento = new DateTime(2012, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Nicole",
                            Telefono = "1234-5678"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Rivera",
                            Email = "claudia.rivera@colegio.edu",
                            FechaNacimiento = new DateTime(1987, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Claudia",
                            Telefono = "2345-6789"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Torres",
                            Email = "amilcar.torres@colegio.edu",
                            FechaNacimiento = new DateTime(1985, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Amilcar",
                            Telefono = "3456-7890"
                        });
                });

            modelBuilder.Entity("ColegioSanJose.Models.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Expedien__3214EC0777FEFBDB");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Expedientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlumnoId = 1,
                            FechaInscripcion = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 1,
                            NotaFinal = 85.5m,
                            Observaciones = "Buen desempeño en examenes"
                        },
                        new
                        {
                            Id = 2,
                            AlumnoId = 1,
                            FechaInscripcion = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 2,
                            NotaFinal = 90.0m,
                            Observaciones = "Excelente participacion"
                        },
                        new
                        {
                            Id = 3,
                            AlumnoId = 2,
                            FechaInscripcion = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 1,
                            NotaFinal = 78.0m,
                            Observaciones = "Necesita mejorar en tareas"
                        },
                        new
                        {
                            Id = 4,
                            AlumnoId = 3,
                            FechaInscripcion = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 3,
                            NotaFinal = 92.5m,
                            Observaciones = "Destacado en debates"
                        });
                });

            modelBuilder.Entity("ColegioSanJose.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Materias__3214EC07B5F51A06");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "MAT101",
                            Creditos = 4,
                            Descripcion = "Algebra y calculo basico",
                            Nombre = "Matematicas"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CNT201",
                            Creditos = 3,
                            Descripcion = "Biologia, fisica y quimica",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "HIS301",
                            Creditos = 2,
                            Descripcion = "Historia universal y nacional",
                            Nombre = "Historia"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "LIT401",
                            Creditos = 3,
                            Descripcion = "Analisis literario y redaccion",
                            Nombre = "Literatura"
                        });
                });

            modelBuilder.Entity("ColegioSanJose.Models.Expediente", b =>
                {
                    b.HasOne("ColegioSanJose.Models.Alumno", "Alumno")
                        .WithMany("Expedientes")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Expedientes_Alumnos");

                    b.HasOne("ColegioSanJose.Models.Materia", "Materia")
                        .WithMany("Expedientes")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Expedientes_Materias");

                    b.Navigation("Alumno");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ColegioSanJose.Models.Alumno", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("ColegioSanJose.Models.Materia", b =>
                {
                    b.Navigation("Expedientes");
                });
#pragma warning restore 612, 618
        }
    }
}
